server:
  port: 9020

spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.159:8848
        username: nacos #nacos的账号
        password: nacos #nacos的密码
        namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2

dubbo:
  registry:
    address: nacos://192.168.31.159:8848 #注册地址
    parameters:
      namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2
    group: dubbo
  application:
    name: dubbo-consumer #应用名
  consumer:
    timeout: 30000 #超时时间
  metadata-report:
    address: nacos://192.168.31.159:8848:8848
    group: dubbo
    parameters:
      namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2
  config-center:
    address: 192.168.31.159
    port: 8848
    protocol: nacos
    group: dubbo
    namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2