server:
  port: 9010

spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.159:8848
        username: nacos #nacos的账号
        password: nacos #nacos的密码
        namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2
dubbo:
  registry:
    address: nacos://192.168.31.159:8848
    parameters:
      namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2
    group: dubbo
  metadata-report:
    address: nacos://192.168.31.159:8848
    group: dubbo
    parameters:
      namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2
  config-center:
    address: 192.168.31.159
    port: 8848
    protocol: nacos
    group: dubbo
    namespace: 302d4c8d-f9e7-4e10-a013-f378038057b2
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 29012
  scan:
    base-packages: com.ch.study.dubboprovider.impl
  provider:
    timeout: 30000