server:
  port: 8091

spring:
  application:
    name: spring-boot-mybatis-application
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.12:8848
        username: nacos #nacos的账号
        password: nacos #nacos的密码
        namespace: 8905c066-da6f-4694-9d52-1bf657349617
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: 8905c066-da6f-4694-9d52-1bf657349617
        group: DEFAULT_GROUP
        flow-data-id: common-sentinel-flow-rules.json
        degrade-data-id: common-sentinel-degrade-rules.json
    sentinel:
      transport:
        dashboard: 192.168.31.12:8090 #sentinel控制台ip:端口号
        port: 8719 #sentinel客户端与控制台通讯端口,当被占用时会向上兼容,使用8720端口
        eager: true #关闭懒加载，体现在项目启动后dashboard就能看到
      datasource:
        ds1: #这个随便填即可,不要和下面的命名冲突就行
          nacos: #使用nacos为数据源
            server-addr: ${spring.cloud.nacos.discovery.server-addr}  #nacos的ip:端口号
            namespace: ${spring.cloud.nacos.discovery.namespace}
            dataId: common-sentinel-rules.json #nacos中流控配置文件的data_id
            groupId: DEFAULT_GROUP #nacos中流控配置文件的分组,我们这里为了方便管理配置文件,我们将所有配置文件都放到SENTINTL分组下
            data-type: json
            rule-type: flow #规则模式 flow-流控 degrade-降级 system-系统 param-flow-热点规则 authority-授权
            username: nacos #nacos的账号
            password: nacos #nacos的密码

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.ch-home.fun:12010/db1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: vhVGI0OXn0NvpaVA
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  global-config:
    db-config:
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
